<<<<<<< HEAD
project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Sequence Paper"
  page-footer:
    right: ""
    left: ""

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    code-fold: true 
execute:
  echo: true
  cache: false
<<<<<<< HEAD
=======
=======
project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Sequence Paper"
  page-footer:
    right: ""
    left: ""

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    code-fold: true 
execute:
  echo: true
  cache: false
>>>>>>> 0bb5708df9c75a9e38caac62086374af26ebceae
>>>>>>> ba3558bb26c5dbb753dc04b52e66098c019d1583
